In [86]:
#First Python work - opening data
import pandas as pd
import numpy as np
pd.set_option('display.max_rows',20)

AllTablesFilePath = 'C:\Users\hp dv5\Desktop\Git Bash Prova\OpenSAP\File Testing\\'

In [120]:
skiprows = [1]
skipfooter = 1
#skiprows = [1] the second row is only --------------------
#On the file row 9912 says '(9908 rows affected)'
sep=';'        #the file is   semi colon separated
dateparse = lambda x: pd.datetime.strptime(x, '%y%m%d')

#MARA table values for extraction
TableFileName = 'mara.csv'
TableFilePath = AllTablesFilePath + TableFileName
index_col = [0,1]          #the keyfield are the first two coloumns
usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]  #the column we need for our work

maraTable = pd.read_csv(TableFilePath, sep=sep, skiprows = skiprows, na_values = ['00000000'], \
                        parse_dates=[2,4],index_col = index_col, usecols=usecols ) 

# engine='c',skipfooter =skipfooter, low_memory=False, skipfooter=skipfooterinfer_datetime_format=Truedate_parser=dateparse, 
# se utilizzo engine = 'python' posso prendere lo skipfooter ma perdo la comprensione delle colonne di tipo data che hanno valori nulli

maraTable
#DEVO CANCELLARE L'ULTIMA RIGA

                                          ERSDA     ERNAM          LAEDA     \
MANDT                MATNR
100                  000000000000000001 2014-02-26  DCIROCCO     2014-02-26
                     0000110            2006-01-24  PICARDI      2010-09-29
                     0000120            2006-01-24  PICARDI      2010-09-29
                     0001070            2006-01-24  PICARDI      2010-09-29
                     0001080            2006-01-24  PICARDI      2010-09-29
                     0001090            2006-01-24  PICARDI      2010-09-29
                     0001425            2006-01-24  PICARDI      2008-03-18
                     0002130            2006-01-24  PICARDI      2009-03-12
                     0002140            2006-01-24  PICARDI      2009-03-12
                     0002150            2006-01-24  PICARDI      2009-03-12
...                                            ...           ...        ...
300                  RIADDEBITI_CONTR   2007-02-20  MASCARINI           NaT
                     RIADDEBITI_TERZI   2007-02-20  MASCARINI    2007-02-20
                     RICAVI_DIV_SEDE    2007-02-20  MASCARINI           NaT
                     RICAVI_DIV_STAB    2007-02-20  MASCARINI           NaT
                     SMALTIMENTO_RIFIUT 2005-11-04  DIGREGORIO   2007-02-20
                     STUDI_STABILITA    2005-11-04  DIGREGORIO   2007-02-20
                     T                  2006-08-29  CODELUPPI           NaT
                     TEST               2006-08-29  CODELUPPI           NaT
                     TRASPORTO          2005-11-04  DIGREGORIO   2007-02-20
(9908 rows affected) NaN                       NaT           NaN        NaT

                                         AENAM         VPSTA            \
MANDT                MATNR
100                  000000000000000001  DCIROCCO      KDELBSCQGZX
                     0000110             LRIZZO        KCVEDLQBGZXS
                     0000120             LRIZZO        KCVEDLQBGZXS
                     0001070             LRIZZO        KCVEDLQBGZXS
                     0001080             LRIZZO        KCVEDLQBGZX
                     0001090             LRIZZO        KCVEDLQBGZXS
                     0001425             ICMDEV        KCVEDALQBGZXS
                     0002130             LRIZZO        KCVEDLQBGZXS
                     0002140             LRIZZO        KCVEDLQBGSZX
                     0002150             LRIZZO        KCVEDLQBGSZX
...                                               ...              ...
300                  RIADDEBITI_CONTR                  KV
                     RIADDEBITI_TERZI    MASCARINI     KVX
                     RICAVI_DIV_SEDE                   KV
                     RICAVI_DIV_STAB                   KV
                     SMALTIMENTO_RIFIUT  MASCARINI     KVX
                     STUDI_STABILITA     MASCARINI     KV
                     T                                 DA
                     TEST                              DA
                     TRASPORTO           MASCARINI     KV
(9908 rows affected) NaN                          NaN              NaN

                                         PSTAT            LVORM  MTART  MBRSH  \
MANDT                MATNR
100                  000000000000000001  KDELBSCQG               ZRIC   P
                     0000110             KCVEDLQBGS              ZPRI   P
                     0000120             KCVEDLQBGS              ZPRI   P
                     0001070             KCVEDLQBGS              ZPRI   P
                     0001080             KCVEDLQBG               ZPRI   P
                     0001090             KCVEDLQBGS              ZPRI   P
                     0001425             KCVEDALQBGS             ZFIN   P
                     0002130             KCVEDLQBGS              ZPRI   P
                     0002140             KCVEDLQBGS              ZPRI   P
                     0002150             KCVEDLQBGS              ZPRI   P
...                                                  ...    ...    ...    ...
300                  RIADDEBITI_CONTR    KV                      ZSER   P
                     RIADDEBITI_TERZI    KV                      ZSER   P
                     RICAVI_DIV_SEDE     KV                      ZSER   P
                     RICAVI_DIV_STAB     KV                      ZSER   P
                     SMALTIMENTO_RIFIUT  KV                      ZSER   P
                     STUDI_STABILITA     KV                      ZSER   P
                     T                   DA                      PROD   M
                     TEST                DA                      PROD   M
                     TRASPORTO           KV                      ZSER   P
(9908 rows affected) NaN                             NaN    NaN    NaN    NaN

                                         MATKL      BISMT               MEINS  \
MANDT                MATNR
100                  000000000000000001  BS200                          NR
                     0000110             802                            KG
                     0000120             802                            KG
                     0001070             203                            KG
                     0001080             203                            KG
                     0001090             107                            KG
                     0001425             C01                            NR
                     0002130             443                            NR
                     0002140             443                            NR
                     0002150             443                            NR
...                                            ...                 ...    ...
300                  RIADDEBITI_CONTR    Z03                            ST
                     RIADDEBITI_TERZI    Z03                            ST
                     RICAVI_DIV_SEDE     Z03                            ST
                     RICAVI_DIV_STAB     Z03                            ST
                     SMALTIMENTO_RIFIUT  Z03                            ST
                     STUDI_STABILITA     Z03                            ST
                     T                                                  NR
                     TEST                                               NR
                     TRASPORTO           Z03                            ST
(9908 rows affected) NaN                       NaN                 NaN    NaN

                                         BSTME
MANDT                MATNR
100                  000000000000000001
                     0000110
                     0000120
                     0001070
                     0001080
                     0001090
                     0001425
                     0002130
                     0002140
                     0002150
...                                        ...
300                  RIADDEBITI_CONTR
                     RIADDEBITI_TERZI
                     RICAVI_DIV_SEDE
                     RICAVI_DIV_STAB
                     SMALTIMENTO_RIFIUT
                     STUDI_STABILITA
                     T
                     TEST
                     TRASPORTO
(9908 rows affected) NaN                   NaN

[9909 rows x 13 columns]

In [52]:
maraTable.head()

In [50]:
dateparse = lambda x: pd.datetime.strptime(x, '%Y%m%d')

In [121]:
maraTable.dtypes

ERSDA                 datetime64[ns]
ERNAM                         object
LAEDA                 datetime64[ns]
AENAM                         object
VPSTA                         object
PSTAT                         object
LVORM                         object
MTART                         object
MBRSH                         object
MATKL                         object
BISMT                         object
MEINS                         object
BSTME                         object
dtype: object

In [79]:
na_values = {4:0}

In [98]:
maraTable

                                          ERSDA     ERNAM         LAEDA
MANDT                MATNR
100                  000000000000000001 2014-02-26  DCIROCCO      20140226
                     0000110            2006-01-24  PICARDI       20100929
                     0000120            2006-01-24  PICARDI       20100929
                     0001070            2006-01-24  PICARDI       20100929
                     0001080            2006-01-24  PICARDI       20100929
                     0001090            2006-01-24  PICARDI       20100929
                     0001425            2006-01-24  PICARDI       20080318
                     0002130            2006-01-24  PICARDI       20090312
                     0002140            2006-01-24  PICARDI       20090312
                     0002150            2006-01-24  PICARDI       20090312
...                                            ...           ...       ...
300                  REPORT_STABILITA   2006-02-24  DIGREGORIO    20070220
                     RIADDEBITI_CONTR   2007-02-20  MASCARINI     00000000
                     RIADDEBITI_TERZI   2007-02-20  MASCARINI     20070220
                     RICAVI_DIV_SEDE    2007-02-20  MASCARINI     00000000
                     RICAVI_DIV_STAB    2007-02-20  MASCARINI     00000000
                     SMALTIMENTO_RIFIUT 2005-11-04  DIGREGORIO    20070220
                     STUDI_STABILITA    2005-11-04  DIGREGORIO    20070220
                     T                  2006-08-29  CODELUPPI     00000000
                     TRASPORTO          2005-11-04  DIGREGORIO    20070220
(9908 rows affected) NaN                       NaT           NaN       nan

[9908 rows x 3 columns]